Phase 4 - Students and grades
Star-Academy/Summer1400-SE-Team24 pull request #3
Opened 2021-08-01 07:50 UTC by mdyerf

2021-08-04 08:43 UTC, Adibov commented on Students/Program.cs
> +namespace Students
checkout [this lisk](https://stackoverflow.com/questions/360643/is-it-a-bad-practice-to-have-multiple-classes-in-the-same-file), better to have a single class file for each class

2021-08-04 08:43 UTC, Adibov commented on Students/JsonParser.cs
> +        public static IList<T> readList<T>(string path)
liked this idea to use inner static class and generics

2021-08-04 08:43 UTC, Adibov commented on Students/JsonParser.cs
> +            List<T> data = JsonConvert.DeserializeObject<List<T>>(content);
shouldn't it be var?

2021-08-04 08:43 UTC, Adibov commented on Students/Program.cs
> +        static void Main(string[] args)
better to keep main method small and just instantiate other objects in it

2021-08-04 08:43 UTC, Adibov commented on Students/Program.cs
> +            var students = JsonParser.readList<Student>("students.json");
parsing, retrieving answer and printing is happening in a single class/method. Better to separate them

2021-08-06 11:57 UTC, amirarab888 requested changes

2021-08-06 11:57 UTC, amirarab888 commented on Students/Models/StudentWithGrade.cs
> +        public decimal Average { get; set; }
اینم میذاشتید تو همون کلاس 
Student
این کلاس اضافیه

2021-08-06 11:57 UTC, amirarab888 commented on Students/Program.cs
> +            var service = new Students.Sevices.Students(students, grades);
سر این طراحی مشکل دارم

2021-08-06 11:57 UTC, amirarab888 commented on Students/Services/Students.cs
> +                Average = grades.Where(g => g.StudentNumber == s.StudentNumber).Average(g => g.Score)
اردر این کار خیلی بالاست بهترش کنید

2021-08-07 07:59 UTC, mdyerf commented on Students/Program.cs
> +            var service = new Students.Sevices.Students(students, grades);
چه مشکلی؟

2021-08-07 10:06 UTC, FarshidNooshi requested changes

2021-08-07 10:06 UTC, FarshidNooshi commented on Students/Services/JsonParser.cs
> +            StreamReader reader = new StreamReader(path);
از 
var 
استفاده کنید 
در صورت امکان از سینتکس 
using var ...
هم استفاده کنید در کدهاتون
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement

2021-08-07 10:06 UTC, FarshidNooshi commented on Students/Services/Students.cs
> +        private IList<Student> _students;
اون هایی رو که توی کد بجز کانستراکتور تغییر نمیدید رو 
readonly 
بکنید

2021-08-07 12:43 UTC, FarshidNooshi approved these changes

2021-08-13 05:00 UTC, amirarab888 approved these changes

2021-08-14 12:54 UTC, merged