Feat/unit test
Star-Academy/Summer1400-SE-Team24 pull request #5
Opened 2021-08-01 10:11 UTC by Adib-Rezaei

2021-08-04 07:14 UTC, Adibov commented on Inverted-Index/src/tests/KeywordsTest.java
> +    private Set<Doc> docs, newDocs, expected_result;
expected_result must be camelCase

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        testFiles = reader.getFiles("C:\\Repos\\Summer1400-SE-Team24\\Inverted-Index\\src\\tests\\docs");
the docs' path better to be constant and relative (to be able to run on other devices)

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +    public void getTestDocs() throws NotADirectoryException, FileNotFoundException {
exceptions better to be checked whether they will be raised or not.

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        Assert.assertEquals(files.length, 1000);
1000 better to be constant

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        Assert.assertEquals(testDocs.get(0).getWords().size(), 8);
8 better to be constant

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +public class Tester {
this class is testing multiple classes which it shouldn't be happen

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        var mapper = new Mapper();
these instantiating better to be in a different initializing method

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        var result = mapper.mergeMaps(map1, map2);
you are testing 3 method at same time by calling this method which is not unit testing. better to use mocking for each method separately

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        String query = "-exclude ordinary +union";
better to be constant

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        var index = new InvertedIndex(testDocs, new Mapper());
in constructor of this line, you are calling multiple method of multiple classes, So if any of them doesn't work properly, the whole test will be failed. Better to use mocking instead

2021-08-04 07:57 UTC, Adibov commented on Inverted-Index/src/tests/Tester.java
> +        var docs = engine.search(parser.parseQuery(query));
multiple function calls without mocking

2021-08-06 10:22 UTC, amirarab888 requested changes
تعداد تست ها خیلی کم بود, آیا واقعا همه لاجیک کد تست شده؟؟؟

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/keywords/Exclude.java
> +        super(word);
گتر ستر این قد اهمیت نداره که با کلاس پدر پیوندش بدید

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +    public void getTestDocs() throws NotADirectoryException, FileNotFoundException {
اسماتون خوب نیست

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +    public void getTestDocs() throws NotADirectoryException, FileNotFoundException {
غیر از اسم تابع اسم اکسپشن
NotDirectoryException
بهتره

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +        testFiles = reader.getFiles("C:\\Repos\\Summer1400-SE-Team24\\Inverted-Index\\src\\tests\\docs");
مقادیر ثابت در متغیر کانست ریخته بشن

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +        this.testDocs = fileReader.getFilesDocs(testFiles);
بعد از 
Assert
چی کار دارید میکنید؟؟؟

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +        Assert.assertEquals(doc1, doc2);
به جای این کار باید میومدید فیلد های مختلف داک رو چک میکردید ببیند درسته یا نه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +        Assert.assertEquals(testFiles.length, testDocs.size());
هر 
Assertion
در یک تابع تست جدا باید باشه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/FileHandlerTest.java
> +    public void getFilesDocsTest() {
عملیاتی که داره تست میشه باید توی تابع تست انجام بشه, فقط یک سری مقادیر و کلاس های کمکی میتونن در سطح کلاس باشن و تو همه توابع تست استفاده بشن

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/InvertedIndexTest.java
> +
extract methods

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/InvertedIndexTest.java
> +        fakeMap = new HashMap<>();
mockedMap 
اسم بهتریه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/KeywordsTest.java
> +        expected_result = new HashSet<>();
extract methods

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/KeywordsTest.java
> +    public void ordinaryTest(){
تو این تابع و دو تا تابع پایینیش چی رو دارید تست میکنید؟؟؟
در توابعی که 
annotation
تست بالاشون گذاشتید باید یک چیزی مورد تست قرار بگیره

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/MapperTest.java
> +    private final Doc DOC_TEST1 = new Doc("1", Arrays.asList(WORD1, WORD2, WORD3));
new 
کردن ها در 
constructor
انجام بشه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/MapperTest.java
> +        Assert.assertEquals(map.get(WORD1), new HashSet<Doc>() {{add(DOC_TEST1);}});
:))))این همه آکولاد رو چشام گم میکنه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/MapperTest.java
> +        Assert.assertEquals(map.get(WORD1), new HashSet<Doc>() {{add(DOC_TEST1);}});
متغیر تعریف بشه و تو اون ریخته بشه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/QueryParserTest.java
> +
بیش تر از یک خط فاصله کار جالبی نیست

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/QueryParserTest.java
> +        Assert.assertEquals(keywords.get(0).getWord(), "ordinary");
این 
Assertion
ها که داره یک چیز رو تست میکنه اشکال نداره تو یه تابع تست باشه ولی جا هایی که داره ابعاد مختلف یک رفتار رو بررسی میکنه تابع تست جدا باید براش در نظر بگیرید

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchEngineTest.java
> +        };
extract methods

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchEngineTest.java
> +        var parser = new QueryParser();
این چرا این جا 
new
شده؟؟؟

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchEngineTest.java
> +        var index = new InvertedIndex(testDocs, new Mapper());
این چرا ماک نشده؟؟؟

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchEngineTest.java
> +        var parser = new QueryParser();
چرا ماک نشده

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchEngineTest.java
> +public class SearchEngineTest {
تعداد تست ها یه مقدار کمه

2021-08-06 10:22 UTC, amirarab888 commented on Inverted-Index/src/tests/SearchTest.java
> +public class SearchTest {
چرا این کلاس فقط 
before
داره؟؟؟

2021-08-07 10:00 UTC, FarshidNooshi requested changes
بچه ها 
PR 
رو دیدم کلیت خیلی خوب بود چنتا کامنت گذاشتم هندلشون کنید لطفا تا بهتر بشه کارتون

2021-08-07 10:00 UTC, FarshidNooshi commented on Inverted-Index/src/tests/KeywordsTest.java
> +    private final String DUMMY_WORD = "dummyword";
یک 
ArrayList<Doc>
داشته باشید برای اینجا تا کد ساده تر بشه

2021-08-07 10:00 UTC, FarshidNooshi commented on Inverted-Index/src/tests/KeywordsTest.java
> +        expected_result.add(DOC_TEST2);
Assertion
ندارید برای تست های این کلاس ؟

2021-08-07 10:00 UTC, FarshidNooshi commented on Inverted-Index/src/tests/KeywordsTest.java
> +        expected_result.add(DOC_TEST4);
برای اینجا هم همینطور 
Assertion 
چرا نیست ؟

2021-08-07 10:00 UTC, FarshidNooshi commented on Inverted-Index/src/tests/QueryParserTest.java
> +        Assert.assertEquals(keywords.get(0).getWord(), "ordinary");
من هم با امیرحسین موافقم اینجا بهتره سه تا تست بنویسید تا مسئولیت تابع جزئی تر باشن

2021-08-07 10:00 UTC, FarshidNooshi requested changes
بچه ها 
PR 
رو دیدم کلیت خیلی خوب بود چنتا کامنت گذاشتم هندلشون کنید لطفا تا بهتر بشه کارتون

2021-08-07 12:42 UTC, FarshidNooshi requested changes

2021-08-07 12:42 UTC, FarshidNooshi commented on Inverted-Index/src/tests/InvertedIndexTest.java
> +public class InvertedIndexTest {
تعداد تست های کلاس کم هستش

2021-08-07 12:42 UTC, FarshidNooshi commented on Inverted-Index/src/tests/SearchEngineTest.java
> +
تعداد تست ها کم هستش برای کلاس

2021-08-13 04:58 UTC, amirarab888 approved these changes

2021-08-14 15:32 UTC, FarshidNooshi approved these changes

2021-08-15 04:52 UTC, merged