Phase5 TDD
Star-Academy/Summer1400-SE-Team24 pull request #6
Opened 2021-08-03 11:38 UTC by Adib-Rezaei

2021-08-06 11:48 UTC, amirarab888 requested changes

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/FileHandlerTest.cs
> +        public void getFilesDocsTest() {
ابعاد مختلف یک رفتار باید در توابع تست جدا, تست بشن

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/FileHandlerTest.cs
> +    public class FileHandlerTest
چرا این جا هم 
fileReader 
تست شده هم
DirectoryReader
هم
Doc?
هر کدوم در کلاس جدا

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +            FileReader fileReader = new FileReader();
چرا ماک نشدن؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +            IDirectoryReader reader = new DirectoryReader();
چرا ماک نشده؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +        public void invertedIndexGetTest() {
چرا فقط تعداد تست شده؟؟؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +        public void invertedIndexGetTest() {
توابع دیگری برای تست اجزا 
result
هم بزنید

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        private readonly Doc DOC_TEST4 = new Doc("4", new List<string>(){"here"});
چرا این جا 
new 
شدن؟ باید اگر مرتبط به همه توابع تست هست در 
constructor
و اگر مربوط به یک تست هست, در همون تابع تست 
new
بشن

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        {
extract methods.

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        public void IncludeTest(){
چی تست شده این جا؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        public void ExcludeTest(){
چی تست شده این جا؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        public void OrdinaryTest(){
چی تست شده این جا؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/MapperTest.cs
> +        public void mergeMapsTest() {
extract methods

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/SearchTest.cs
> +            FileReader fileReader = new FileReader();
چرا ماک نشده؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/SearchTest.cs
> +            IDirectoryReader reader = new DirectoryReader();
چرا ماک نشده؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/SearchTest.cs
> +            var parser = new QueryParser();
چرا ماک نشده؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/SearchTest.cs
> +            var index = new InvertedIndex.Search.InvertedIndex(testDocs, new Mapper());
چرا ماک نشده؟

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex.Test/SearchTest.cs
> +            };
تابع بشه

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex/FileHandler/FileReader.cs
> +                    words.AddRange(lineWords);
تابع بشه

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex/FileHandler/FileReader.cs
> +                    words.AddRange(lineWords);
تابع بشه

2021-08-06 11:48 UTC, amirarab888 commented on Phase5-TDD/InvertedIndex/FileHandler/FileReader.cs
> +                    List<string> lineWords = Regex.Replace(line, "[^a-zA-Z0-9]", " ")
مقادیر ثابت در متغیر کانست ریخته بشه

2021-08-07 10:17 UTC, FarshidNooshi requested changes
بچه ها 
.gitignore 
رو چک کنید و فایل های اضافی رو ایگنور کنید 
پروژه تعداد فایل هاش خیلی زیاد هست

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +            FileInfo[] testFiles = reader.getFiles("/media/adib/Local Disk3/Projects/Star-Academy/Summer1400-SE-Team24/Phase5-TDD/InvertedIndex.Test/docs");
این ادرس ها رو توی یه فایل ثابت توی پروژه بذارید بعنوان یک 
map
بعد از روی اون کلاس از یک فیلد 
static 
که این ادرس ها رو داره فراخوانی کنیدشون بهتر هست

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex.Test/InvertedIndexTest.cs
> +            FileInfo[] testFiles = reader.getFiles("/media/adib/Local Disk3/Projects/Star-Academy/Summer1400-SE-Team24/Phase5-TDD/InvertedIndex.Test/docs");
مثل جاوا اینجا هم سعی کنید از 
var 
استفاده کنید

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex.Test/KeywordTest.cs
> +        public void Dispose()
این متد چرا 
Assertion
 داره بدون اینکه 
 fact 
 شده باشه یا ازش جایی استفاده شده باشه

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex.Test/MapperTest.cs
> +            map3.Add("word3", new HashSet<Doc>() {new Doc("1", new List<string>())});
extract method anjam bedid

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex.Test/QueryParserTest.cs
> +            Assert.Equal("ordinary", keywords[0].GetWord());
3 ta method konid inja ro baraye har assertion

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex/FileHandler/FileReader.cs
> +        foreach (var file in files) {
indent code ro check konid

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex/FileHandler/FileReader.cs
> +        public IList<string> getFileWords(FileInfo file)
متد خیلی طولانیه 
شکسته بشه به چنتا متد

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex/Keywords/Union.cs
> +            return newDocs;
indent konid code ro ye dor ina intori nabashan

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex/Search/InvertedIndex.cs
> +        private IDictionary<string, HashSet<Doc>> map;
readonly

2021-08-07 10:17 UTC, FarshidNooshi commented on Phase5-TDD/InvertedIndex/UserInterface/IUserIO.cs
> +            throw new NotImplementedException();
چرا ؟

2021-08-13 04:55 UTC, amirarab888 approved these changes

2021-08-14 15:33 UTC, FarshidNooshi approved these changes

2021-08-15 04:54 UTC, merged